### ISSUE TITLE
examples/general/sum with qthread

### ISSUE THREAD

**Issue by avsej** [RaftLib/RaftLib#83] opened 2019-09-07 09:46 UTC
I'm trying to run the examples to explore the library, but it seems like with qthread 1.14 on my Linux box, the `examples/general/sum` does not work. It does not output anything. And the `Sum` kernel is not getting executed.

How I can diagnose what might gone wrong?

I'm using Fedora 30.
`rpm -ql qthread qthread-devel` output: [output-rpm-ql-qthread.txt](https://github.com/RaftLib/RaftLib/files/3586466/output-rpm-ql-qthread.txt)
cmake output: [output-cmake.txt](https://github.com/RaftLib/RaftLib/files/3586467/output-cmake.txt)
make output: [output-make.txt](https://github.com/RaftLib/RaftLib/files/3586470/output-make.txt)

**Comment by jonathan-beard** [comment] 2019-09-07 18:53
Qthreads is a bit finicky at times. I'm working to reproduce the issue. I made a fresh environment in this container: [docker file](https://cloud.docker.com/repository/docker/jonbea01/raftlib-debug)

In the past I've run into issues inside qthreads where threads wasn't being initialized without asserts turned on. I'll start there and see if I can find the issue. I'm going to be a bit short of time today to work through, but will by the end of next week.

**Comment by jonathan-beard** [comment] 2019-09-07 18:55
Could be related to Issue #65, need to investigate.

**Comment by jonathan-beard** [comment] 2020-05-10 01:40
@avsej, if you have any other info, please let me know. I still can't reproduce this bug. Closing for now, we can reopen if you're still having the same problem. 

Cheers!,
Jonathan

**Closed by jonathan-beard** 2020-05-10 01:40 UTC
Labels: question
