### ISSUE TITLE
Question: are std::string ports supported?

### ISSUE THREAD

**Issue by Cthutu** [RaftLib/RaftLib#71] opened 2018-08-03 15:13 UTC
I've been playing around with raftlib, but I've hit a brick wall when trying to output strings:  Here is my test kernel:

```C++
class Sum : public raft::kernel
{
public:
    Sum()
        : raft::kernel()
    {
        // Define ports
        input.addPort<T>("input_a", "input_b");
        output.addPort<std::string>("sum");
    }

    raft::kstatus run() override
    {
        T a, b;
        input["input_a"].pop(a);
        input["input_b"].pop(b);

        auto c(output["sum"].template allocate_s<std::string>());
        std::stringstream ss;
        ss << a << " + " << b << " = " << (a + b) << " [" << GetCurrentThreadId() << "]\n";
        *c = ss.str();

        return raft::proceed;
    }
};
```

This crashes inside `map::exe()` after completing the kernels and deallocating memory.  I've tried `allocate` and `send` and that doesn't run at all.

So my question is: Are std::string typed ports supported or am I doing something stupid?

**Comment by Cthutu** [comment] 2018-08-03 15:21
OK, further investigation shows that there are problems with assigning `ss,str()` to `c`.  Not sure why that would screw things up.  By replacing `*c = ss.str()` with `*c = "test"`, it works.

**Comment by jonathan-beard** [comment] 2018-08-03 20:28
So when you allocate the memory you need to dereference the pointer. Technically this isn't a bare pointer, however, given the number of C/C++ programmers I had complain about allocate without a pointer dereference. These allocations are garbage collected as well, so basically the string you allocate here, if you pass it to multiple kernels it's the same pointer and you don't have to worry about the locks or synchronization yourself. Please see the "getting started guide" here: https://github.com/RaftLib/RaftLib/wiki/Getting-Started

**Comment by Cthutu** [comment] 2018-08-03 22:15
I looked at the wiki but it doesn't explain how to handle std::string, because if I replace int64_t with std::string I get a crash, so the behaviour is not the same.  I looked at the examples too and I couldn't find an example of using std::string correctly.  So what should I do to handle strings on ports?  I still don't understand what is going wrong from your description above.  Perhaps an example in the wiki where you can dereference the type?

**Comment by jonathan-beard** [comment] 2018-08-08 20:54
Hi. Ok. Let's try this: 

```cpp
template< typename T > class sum : public raft::kernel
{
public:
   sum() : raft::kernel()
   {
      input. template addPort< T >( "input_a", "input_b" );
      output.template addPort< std::string >( "sum" );
   }
   virtual raft::kstatus run()
   {
      T a,b; 
      input[ "input_a" ].pop( a );
      input[ "input_b" ].pop( b );
      /** allocate mem directly on queue **/
      auto c( output[ "sum" ].template allocate_s< std::string >() );
      std::stringstream ss;
      ss << a << " + " << b << " = " << (a + b);
      (*c) = ss.str();
      /** mem automatically freed upon scope exit **/
      return( raft::proceed );
   }
};
```

I added this as a test case, will add to the wiki documentation shortly. This example compiles and runs well under Linux (kernel version 4.15) and Mac OS X 10.x (tried two). I'll run on windows as well soon. I've a few more bug fixes to incorporate first. 

Does this example answer the question? Changing the type of port in the constructor and using the type in the allocator does the trick. Given that this example is almost identical to your example above...I'm honestly not sure what's going on with your build. Is there a chance there's something outside of this code snippet that's causing the fault. BTW, the code for the complete running example is in _testsuite/allocate_s_string.cpp_

If you're in to details, under the hood, when the allocator is called you'll get one of two differing behaviors depending on the size of the object. It'll either be allocated with the constructor called in place inline with the queue itself or it'll be allocated in an external memory pool and the same pointer passed around transparently through the stream.

**Comment by Cthutu** [comment] 2018-08-13 14:33
I don't see a difference with that code with what I have (except for the Windows to GetCurrentThreadId).

**Comment by Cthutu** [comment] 2018-08-13 14:35
Here's the code that uses the kernel:

```C++
    const auto count(1000);
    using type_t = int64_t;

    using gen = raft::random_variate<default_random_engine, uniform_int_distribution, type_t>;
    using sum = Sum<type_t>;

    gen a(count), b(count);
    sum s;
    raft::print<string> p (std::cout);
    raft::map m;

    m += a >> s["input_a"];
    m += b >> s["input_b"];
    m += s >> p;

    m.exe();
```

**Comment by Cthutu** [comment] 2018-08-13 14:38
I noticed the different allocators based on cache lines.  Here is a screenshot of the crash: https://imgur.com/a/kUeqf5V

I've noticed if I reduce the count to 100, it works.

**Comment by jonathan-beard** [comment] 2018-08-14 20:50
Interesting. Works perfectly on Linux and Mac OS X with all optimizations and any count. I'll look over the screen shot more carefully tonight. My hunch is that there is either something wonky going on with the way RaftLib is using calloc in this instance (maybe pointer corruption or heap corruption).

**Comment by jonathan-beard** [comment] 2018-11-19 22:22
Ok, I've run the example in VS2017 and can't seem to reproduce the issue. Any chance you've made progress in narrowing it down since last you reported the issue?

**Comment by jonathan-beard** [comment] 2019-01-23 17:23
Any chance anybody else has been able to reproduce? I've a fresh windows VM now, will try again this weekend.

**Comment by jonathan-beard** [comment] 2020-05-14 02:48
Closing this issue, strings work, added test case in ```testsuite/stringAlloc.cpp``` with merge #104

**Closed by jonathan-beard** 2020-05-14 02:48 UTC
