### ISSUE TITLE
Mistakenly reports "C++11 alignas unsupported" with g++ 6.3

### ISSUE THREAD

**Issue by lorenzhs** [RaftLib/RaftLib#31] opened 2017-03-17 15:16 UTC
It seems that `__alignof_is_defined` isn't defined despite alignof being supported. This causes a truckload of warnings.

Since the `ALIGNOF` macro is never used, is there any reason not to remove it?

I'm using g++ 6.3 on Debian unstable, if that's helpful. No messages are emitted when using clang++ 4.0.

**Comment by jonathan-beard** [comment] 2017-03-21 10:02
Just go the issue to reproduce on the unstable branch. built g++ 6.3 from scratch couldn't get the same message. Will check tonight to see if I can find the disconnect. Just to confirm, can you give me the compile flags? Were there any additional ones passed to cmake or just the default?

Thanks!,
J

**Comment by lorenzhs** [comment] 2017-03-21 10:22
Sorry, didn't see the dev branch. However I can't currently compile RaftLib (master or dev) because a recent gcc update seems to have broken it (compiler segfaults)... It fails before I get the warning on dev but I still get the warning on master:

```
/usr/bin/c++   -DL1D_CACHE_LINE_SIZE=64 -DLIBCOMPILE=1 -DRDTSCP=1 -Isrc -I../src -I../raftinc -I../ -I../git-dep/cmdargs/include -I../git-dep/shm/include -W -Wall -Wextra -Wpedantic -std=gnu++14 -MD -MT src/CMakeFiles/raft.dir/mapbase.cpp.o -MF src/CMakeFiles/raft.dir/mapbase.cpp.o.d -o src/CMakeFiles/raft.dir/mapbase.cpp.o -c /ssd_home/3rdpartycode/RaftLib/src/mapbase.cpp
In file included from ../raftinc/fifo.hpp:35:0,
                 from ../raftinc/port_info.hpp:34,
                 from ../raftinc/portmap_t.hpp:26,
                 from ../raftinc/portiterator.hpp:28,
                 from ../raftinc/portbase.hpp:26,
                 from ../raftinc/port.hpp:32,
                 from ../raftinc/kernel.hpp:29,
                 from ../raftinc/mapbase.hpp:42,
                 from /ssd_home/3rdpartycode/RaftLib/src/mapbase.cpp:32:
../raftinc/blocked.hpp:40:87: note: #pragma message: C++11 alignas unsupported :( Falling back to compiler attributes
 #    pragma message("C++11 alignas unsupported :( Falling back to compiler attributes")
                                                                                       ^
../raftinc/blocked.hpp:53:87: note: #pragma message: C++11 alignof unsupported :( Falling back to compiler attributes
 #    pragma message("C++11 alignof unsupported :( Falling back to compiler attributes")
                                                                                       ^
In file included from ../raftinc/ringbufferheap.tcc:25:0,
                 from ../raftinc/ringbufferbase.tcc:66,
                 from ../raftinc/ringbuffer.tcc:34,
                 from ../raftinc/port.hpp:37,
                 from ../raftinc/kernel.hpp:29,
                 from ../raftinc/mapbase.hpp:42,
                 from /ssd_home/3rdpartycode/RaftLib/src/mapbase.cpp:32:
../raftinc/ringbufferheap_abstract.tcc: In lambda function:
../raftinc/ringbufferheap_abstract.tcc:371:64: internal compiler error: Segmentation fault
                         local_insert_helper( *begin, *end, sig );
                                                                ^
```

**Comment by jonathan-beard** [comment] 2017-03-21 13:03
Had to dig through the C++ header files a bit. Looks like the C++ header files from cstdalign all include stdalign.h. This is all well and good, however that's where the goodness stops. GNU C++ stdalign.h looks like this: 

```cpp
 26 #ifndef _STDALIGN_H
 27 #define _STDALIGN_H
 28 
 29 #ifndef __cplusplus /** problem starts here **/
 30 
 31 #define alignas _Alignas
 32 #define alignof _Alignof
 33 
 34 #define __alignas_is_defined 1
 35 #define __alignof_is_defined 1
 36 
 37 #endif
 38 
 39 #endif  /* stdalign.h */
```
looks like the macro is only expanded to 1 on no c++ for the GNU C++. The Clang stdalign.h file in contrast looks like:
```cpp
#ifndef __STDALIGN_H
   25 #define __STDALIGN_H
   26 
   27 #ifndef __cplusplus
   28 #define alignas _Alignas
   29 #define alignof _Alignof
   30 #endif /** end no c++ **/
   31 
   32 #define __alignas_is_defined 1
   33 #define __alignof_is_defined 1
   34 
   35 #endif /* __STDALIGN_H */
```

This appears to be a bug in the GNU implementation, or feature (not quite sure). The cppreference shows that the macro should be defined, not sure this is actually the case or not. One of them is either wrong, or this is a gray area in the definition. I think the best thing to do in this case is add an or for the C++ standard (C++1x should have the alignof/alignas defined as keywords). I'll make the update tonight. 

Thanks for the catch! I'll close the issue when fixed.

-J

**Comment by lorenzhs** [comment] 2017-03-21 13:42
Well according to cppref, `alignof` and `alignas` are required for a C++11 compiler so you could just test the `__cplusplus` variable: http://stackoverflow.com/a/7132549

**Comment by jonathan-beard** [comment] 2017-03-22 01:27
Closing...will reopen if autobuild on Travis-CI fails. Compiled on Linux w/GCC 6.3 fresh build. Clang of course works as above. Need to check in future if these headers differ on other platforms. Likely.

**Closed by jonathan-beard** 2017-03-22 01:27 UTC
